### ISSUE TITLE
missing `_randomisation` config error

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt-contrib-assessment#161] opened 2022-03-30 14:32 UTC
If the '_randomisation` config is missing from the assessment article, and question banks are disabled, the following line creates an error:
https://github.com/adaptlearning/adapt-contrib-assessment/blob/master/js/adapt-assessmentArticleModel.js#L146

**Comment by oliverfoster** [comment] 2022-08-15 15:50
duplicate of https://github.com/adaptlearning/adapt_framework/issues/3287

**Closed by oliverfoster** 2022-08-15 15:50 UTC
Labels: bug
